name: CI/CD
on :
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  web-deploy:
    name: auto deploy
    runs-on: ubuntu-latest

    steps:
    - name: get latest code
      uses: actions/checkout@v3

    - name: FTP Deploy
    # You may pin to the exact commit or the version.
    # uses: SamKirkland/FTP-Deploy-Action@8a24039354ee91000cb948cb4a1dbdf1a1b94a3c
      uses: SamKirkland/FTP-Deploy-Action@v4.0.0
      with:
        # ftp server
        server: undangan.kaitodecode.com
        # ftp username
        username: undangan@undangan.kaitodecode.com
        # ftp password
        password: asdfdfgfhjyt6yrtedsawZSXCDVBNMJK,LIOUKYTREWQASDFGBHNMJKLIOUYTGRFDSAWQ23E4RTGFHJKUIO8UYJHGVBCF
        # Server port to connect to (read your web hosts docs)
        port: 21
        # protocol to deploy with - ftp, ftps, or ftps-legacy
        protocol: ftp
        # An array of glob patterns, these files will not be included in the publish/delete process
        exclude: |
          */.git
          */.git/**
          */node_modules/*
          */vendor/*
